apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo-svc
spec:
  selector:
    app: jenkins-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30088
  type: NodePort
