apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: jenkins-demo
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}
